#!/usr/bin/zsh
autoload -U compinit
compinit

CONFIG_PATH="/home/kyle/Documents/config"

# Clipboard.
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# Current Projects
alias sudoku='cd ~/Documents/sudoku'
#alias portfolio='cd ~/Documents/portfolio'
#alias cs910='cd ~/Documents/cs910/cw'
#alias cs904='cd ~/Documents/"cs904: Computational Biology"'
#alias cs910='cd ~/Documents/"cs910: Data Analytics"'
#alias cs402='cd ~/Documents/"cs402: High Performance Computing"'
alias lucidlab='cd ~/Documents/lucidlab'
#alias cs413='cd ~/Documents/"cs413: Image and Video"'
#alias cs419='cd ~/Documents/"cs419: Quantum Computing"'

# Directories.
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias /='cd /'
alias ~='cd ~'
alias mkdir='mkdir -pv'
mkcd() { mkdir -p $1; cd $1 }
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias untar='tar -xvf'
alias cl='clear && ls -al'

# Git.
alias log='git log --pretty=format:"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --date=short --reverse'
alias diff='git diff'
alias repos='mgitstatus -c --no-upstream ~/Documents'

upload() {
  branchName=$(git branch --show-current)
  git add . && git commit -m $1 && git push origin $branchName
}

# Media Controller.
alias song='playerctl metadata --format "Now playing: {{ artist }} - {{ album }} - {{ title }}"'
alias next='playerctl next && sleep 1 && song'
alias previous='playerctl previous && sleep 1 && song'
alias pause='playerctl pause'
alias unpause='playerctl play'

# Network.
alias ip='curl icanhazip.com'

# Packages.
alias pac='sudo pacman'
alias apt-get='sudo apt-get'
alias pip='sudo pip'
alias docker='sudo docker'

# Random.
alias lenny='echo "\_(ツ)_/¯" | pbcopy && pbpaste'
alias fire='aafire -driver curses'
alias symbols='cat ${CONFIG_PATH}/docs/symbols'
alias editsymbols='vim ${CONFIG_PATH}/docs/symbols'

# Redshift.
alias night='redshift -O 4250 &> /dev/null'
alias day='redshift -x &> /dev/null'

# Security.
alias password='openssl rand -base64 20'
alias sha='shasum -a 256'

# Shortcuts (Config).
alias config='cd ${CONFIG_PATH}'
alias commands='vim ${CONFIG_PATH}/docs/commands'
alias keybinds='cat ${CONFIG_PATH}/docs/keybinds'
alias aliases='vim ${CONFIG_PATH}/aliases/global && source ~/.zshrc'
alias startup='vim ${CONFIG_PATH}/startup.py'
alias todo='vim ~/Documents/todo'
alias zshrc='vim ~/.zshrc && source ~/.zshrc'
alias torrents='cd ~/Downloads/torrents/'

# Shortcuts (Directories).
alias docs='cd ~/Documents'
alias desk='cd ~/Desktop'
alias pics='cd ~/Pictures'
alias vids='cd ~/Videos'
alias home='cd ~/Documents && reload'

# Shutdown.
alias shutdown='shutdown -h now'
alias restart='shutdown -r now'
alias lock='xdg-screensaver lock'

# Terminal.
alias l='ls -Alh --color=auto'
alias ll='ls -Alh --color=auto'
alias ls='ls --color=auto'
alias la='ls -Alh --color=auto'
alias grep='grep --color=auto'
alias h='history'
alias hs='history | grep'
alias c='clear'
alias neofetch='neofetch --source ${CONFIG_PATH}/media/goose.txt'
alias v='vim'
alias urxvt-config='vim ${CONFIG_PATH}/.Xresources && xrdb ${CONFIG_PATH}/.Xresources'

# Downloads.
alias youtube-audio='youtube-dl -x -f bestaudio'
alias youtube-metadata='youtube-dl -qse --get-title --get-duration --get-description'

# Web (Uses default browser).
alias google='xdg-open google.co.uk &'
alias youtube='xdg-open youtube.co.uk &'
alias github='xdg-open github.com &'
alias amazon='xdg-open amazom.co.uk &'
alias netflix='xdg-open netflix.co.uk &'
alias gslides='xdg-open https://docs.google.com/presentation/u/0/ &'
alias gsheets='xdg-open https://docs.google.com/spreadsheets/u/0/ &'
alias gdocs='xdg-open https://docs.google.com/document/u/0/ &'

# DON'T FORGET TO RELOAD. Config should automatically reload when this file is closed.
alias reload='clear && source ~/.zshrc'
