#!/usr/bin/zsh

# Assigns apps to certain file types.
alias -s {txt,sh}=vim                  # Scripts/Text --> Vim
alias -s {md}=typora                   # Markdown     --> Typora
alias -s {py,c,cpp,java}=code          # Programming  --> Code
alias -s {png,jpg,jpeg,bmp,gif}=feh    # Images       --> Feh
